language: php
dist: xenial

cache:
  directories:
    - ${HOME}/.composer/cache/files

env:
  global:
    - COMPOSER_OPTIONS=

jobs:
  include:
    - stage: Smoke Testing
      php: "7.3"

    # Test remaining supported PHP versions
    - stage: Test
      php: "7.1"
    - stage: Test
      php: "7.2"
    - stage: Test
      php: "7.4"

    # Test against lowest supported dependencies
    - stage: Test
      php: "7.1"
      env:
        - COMPOSER_OPTIONS=--prefer-lowest

before_script:
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable ${COMPOSER_OPTIONS}

script:
  - vendor/bin/phpunit -v
